services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-airflow
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./db/Airflow.sql:/docker-entrypoint-initdb.d/Airflow.sql
      - ./db/import-cities.sql:/docker-entrypoint-initdb.d/import-cities.sql
      - ./db/worldcities.csv:/var/lib/mysql-files/worldcities.csv
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5