services:
  mysql:
    image: mysql
    container_name: mysql-airflow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
    ports:
      - "3306:3306"
    volumes:
      - ./db/Airflow.sql:/docker-entrypoint-initdb.d/Airflow.sql
